services:
  api:
    build: ./api
    restart: always

  nginx:
    build: ./nginx
    ports:
      - "8080:80" # Truy cập Nginx từ máy thật qua cổng 8080
    depends_on:
      - api

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.4
    command: ["-nginx.scrape-uri", "http://nginx/metrics"]
    depends_on:
      - nginx
    restart: always

  prometheus:
    image: prom/prometheus:v2.37.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules:/etc/prometheus/rules
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana:8.5.2
    ports:
      - "3010:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    restart: always

  node-exporter:
    image: prom/node-exporter:v1.9.1
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100" # Expose cổng 9100 để Prometheus có thể scrape
    restart: always
    pid: host

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.1 
    container_name: cadvisor
    ports:
      - "8081:8080" 
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    restart: always

  alertmanager:
    image: prom/alertmanager:v0.28.1
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
      - ./alertmanager/alertmanager_data:/data
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/data'
    env_file:
      - ./.env
    ports:
      - "9093:9093"
    restart: always

volumes:
  alertmanager_data:
  prometheus_data:
  grafana_data: