global:
  scrape_interval: 1s

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager:9093'

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113'] # "nginx-exporter" là tên service
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  
  - job_name: 'kafka-brokers'
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ['kafka:9999']
  
  - job_name: 'minio-cluster'
    scheme: http
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['minio:9000']


